name: Build Image

on:
 release:
    types: [published]
    push:
      tags:
      - 'v*'
  #  branches: 
  #    - master
  #  schedule:
  #    - cron: 0 8 * * 5
 watch:
   types: [started]

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/lixiangyang1994/linux-amlogic.git /opt/linux-amlogic
        mkdir -p /opt/images/ 
        
    - name: Build Firmware
      run: |
        cd /opt/linux-amlogic
        make meson64_defconfig
        make -j
        sudo cp arch/arm64/boot/Image /opt/images/
        
    - name : Upload packages
      uses: actions/upload-artifact@v2
      if: always()   # 成功才执行
      with:
        name: CoreELEC-T1
        path: /opt/images
